apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # <plural-resource-name>.<group-name>
  name: backups.sample.example.com
spec:
  # REST API => /apis/<group-name>/<api-version-name>
  group: sample.example.com
  version: v1alpha1
  # Namespaced or Cluster
  scope: Namespaced
  names:
    # <plural-resource-name>
    plural: "backups"
    singular: "backup"
    kind: "Backup"
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["replicas"]
          properties:
            replicas:
              type: "integer"
              minimum: 1