version: "3"
services:
  app:
    build:
      context: .
    environment:
      TZ: Japan
      no_proxy: "127.0.0.1,localhost"
    volumes:
      - ./:/go/src/github.com/hohihohi/k8s-client-go-sample